apiVersion: v1
kind: ConfigMap
metadata:
  name: energize-config
data:
  example_config.json: |
    {
        "checkpoints_path": "./experiments/example",
        "statistics_format": "json",
        "energize": {
            "measure_power": {
                "train": true,
                "test": true,
                "num_measurements_test": 30,
                "modules": true
            },
            "model_partition": true,
            "model_partition_n": 2,
            "ensure_gpu_exclusivity": true
        },
        "evolutionary": {
            "generations": 100,
            "lambda": 4,
            "max_epochs": 1000000,
            "mutation": {
                "add_connection": 0.0,
                "remove_connection": 0.0,
                "add_layer": 0.25,
                "reuse_layer": 0.15,
                "remove_layer": 0.25,
                "reuse_module": 0.15,
                "remove_module": 0.25,
                "dsge_layer": 0.15,
                "macro_layer": 0.3,
                "train_longer": 0.2
            },
            "track_mutations": true,
            "fitness_function": [
                {
                    "metric": "accuracy_1",
                    "objective": "maximize",
                    "weight": 1
                },
                {
                    "metric": "power_1",
                    "objective": "minimize",
                    "weight": 15,
                    "conditions": [
                        {
                            "metric": "accuracy_1",
                            "type": "greater_than",
                            "value": 0.8
                        },
                        {
                            "metric": "accuracy_1",
                            "type": "less_than",
                            "value": 0.95
                        }
                    ]
                }
            ]
        },
        "network": {
            "architecture": {
                "reuse_layer": 0.7,
                "macro_structure": [
                    "learning",
                    "model_partition"
                ],
                "output": "softmax",
                "modules": [
                    {
                        "name": "features",
                        "network_structure_init": [
                            1,2,3,4,5
                        ],
                        "network_structure": [
                            0,
                            50
                        ],
                        "levels_back": 1
                    },
                    {
                        "name": "classification",
                        "network_structure_init": [
                            1,2,3,4,5
                        ],
                        "network_structure": [
                            0,
                            25
                        ],
                        "levels_back": 1
                    }
                ]
            },
            "learning": {
                "data_splits": {
                    "evo_train": 0.7,
                    "evo_validation": 0.2,
                    "evo_test": 0.1
                },
                "learning_type": "supervised",
                "default_train_time": 300,
                "augmentation": {
                    "train": {
                        "resize": {
                            "size": 32
                        }
                    },
                    "test": {
                        "resize": {
                            "size": 32
                        }
                    }
                }
            }
        }
    } 