apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- job.yaml

patches:
- path: patches/configmap-patch.yaml
  target:
    kind: ConfigMap
    name: energize-config

labels:
- pairs:
    app: energize 